
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author patel
 */
public class TypingHomeScreen extends javax.swing.JFrame {

    String previewString = "";
    int timeDuration = 5;
    String lorem_ipsum;
    String langPath = "C:\\Users\\patel\\OneDrive\\Documents";

    /**
     * Creates new form HomeScreen
     */
    public TypingHomeScreen() {
        setTitle("Steno Master: Steno Typing Test");

        initComponents();

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo  typing software.jpeg")));

        languageComboBox.setSelectedIndex(0);
        onLanguageSelected();
        
        TimeDurationComboBox.setSelectedIndex(0);

        Dimension dmnsn = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(dmnsn.width / 2 - getSize().width / 2,
                dmnsn.height / 2 - getSize().height / 2,
                getSize().width,
                getSize().height);

        //setSize(MainHomeScreenPanel.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainHomeScreenPanel = new javax.swing.JPanel();
        TimeDurationComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExcerciseList = new javax.swing.JList<>();
        StartTestButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        languageComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        PreviewTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainHomeScreenPanel.setBackground(new java.awt.Color(0, 0, 255));
        MainHomeScreenPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 51, 204)));
        MainHomeScreenPanel.setFont(new java.awt.Font("Arial Unicode MS", 0, 22)); // NOI18N

        TimeDurationComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TimeDurationComboBox.setForeground(new java.awt.Color(0, 0, 102));
        TimeDurationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            {"5 Mins.", "10 Mins.", "15 Mins.", "30 Mins.", "40 Mins.","50 Mins.","60 Mins" }));
    TimeDurationComboBox.setSelectedIndex(0);
    TimeDurationComboBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TimeDurationComboBoxActionPerformed(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Time Duration");
    jLabel1.setMaximumSize(new java.awt.Dimension(150, 25));
    jLabel1.setMinimumSize(new java.awt.Dimension(145, 22));
    jLabel1.setPreferredSize(new java.awt.Dimension(150, 25));

    ExcerciseList.setBackground(new java.awt.Color(153, 255, 153));
    ExcerciseList.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    ExcerciseList.setForeground(new java.awt.Color(102, 102, 0));
    ExcerciseList.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "Excercise 1", "Excercise 2", "Excercise 3",
            "Excercise 4", "Excercise 5", "Excercise 6",
            "Excercise 7", "Excercise 8","Excercise 9",
            "Excercise 10" ,"Excercise 11", "Excercise 12",
            "Excercise 13", "Excercise 14", "Excercise 15",
            "Excercise 16", "Excercise 17", "Excercise 18",
            "Excercise 19", "Excercise 20" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    ExcerciseList.setSelectedIndex(0);
    ExcerciseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            ExcerciseListValueChanged(evt);
        }
    });
    jScrollPane1.setViewportView(ExcerciseList);

    StartTestButton.setBackground(new java.awt.Color(255, 0, 0));
    StartTestButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
    StartTestButton.setForeground(new java.awt.Color(255, 255, 255));
    StartTestButton.setText("Start Test");
    StartTestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    StartTestButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            StartTestButtonActionPerformed(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Language");
    jLabel2.setMaximumSize(new java.awt.Dimension(150, 25));
    jLabel2.setMinimumSize(new java.awt.Dimension(145, 22));
    jLabel2.setPreferredSize(new java.awt.Dimension(150, 25));

    languageComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    languageComboBox.setForeground(new java.awt.Color(0, 0, 102));
    languageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "English", "Hindi"}));
languageComboBox.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        languageComboBoxActionPerformed(evt);
    }
    });

    PreviewTextArea.setEditable(false);
    PreviewTextArea.setColumns(20);
    PreviewTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
    PreviewTextArea.setForeground(new java.awt.Color(0, 0, 153));
    PreviewTextArea.setLineWrap(true);
    PreviewTextArea.setRows(5);
    PreviewTextArea.setText("?? ?????? : ????? ?????? ?????? ?????? ?????? ?? 89 ??? ?? ???? ??? ???? ?? ??? ??. ?? ???? ??? ?? ????? ?? ?? ??????? ??? ???? ?? ??? ??. ?????? ?????? (Somnath Chatterjee) ?? ??????? ?????? ??? ????? ?? ?? ????? ???? ??????? ?? ??? ??? ???? ??? ???????????? ??. ??? ??? ?? ?????? ??? ?? ?????? ??? ?? ???? ???? ?????? ???? ?????? ?????? ?? ?? ?? ?????? ??? ??? ?? ????? ?? ???? ?? ?? ???? ????? ??? ?? ????? ?? ??? ????? ????. ?? ????? ?? ??? ???? ???? ???? '?????? ??' (???????? ???????? ??? ??? ?????? ??? ??? ?? ?????? ??) ?? ?????? ??? ?????? ?? ???? ??? ????? ??? ???? ???. 25 ????? 1929 ?? ??? ?? ?????? ??? ????? ????? ?????? ??? ????? ?????? ?????? ?? ?????-????? ??????? ?? ??????? ??? ???. ??????? ?? ????? ?? ??? ???????? ??????? ???????? ??? ????? ?? ?????? ??. ??? ????? ??????? ??? ???????? ???. 1968 ??? ?????? ?? ???? ??? ????. \n?? ?????? : ????? ?????? ?????? ?????? ?????? ?? 89 ??? ?? ???? ??? ???? ?? ??? ??. ?? ???? ??? ?? ????? ?? ?? ??????? ??? ???? ?? ??? ??. ?????? ?????? (Somnath Chatterjee) ?? ??????? ?????? ??? ????? ?? ?? ????? ???? ??????? ?? ??? ??? ???? ??? ???????????? ??. ??? ??? ?? ?????? ??? ?? ?????? ??? ?? ???? ???? ?????? ???? ?????? ?????? ?? ?? ?? ?????? ??? ??? ?? ????? ?? ???? ?? ?? ???? ????? ??? ?? ????? ?? ??? ????? ????. ?? ????? ?? ??? ???? ???? ???? '?????? ??' (???????? ???????? ??? ??? ?????? ??? ??? ?? ?????? ??) ?? ?????? ??? ?????? ?? ???? ??? ????? ??? ???? ???. 25 ????? 1929 ?? ??? ?? ?????? ??? ????? ????? ?????? ??? ????? ?????? ?????? ?? ?????-????? ??????? ?? ??????? ??? ???. ??????? ?? ????? ?? ??? ???????? ??????? ???????? ??? ????? ?? ?????? ??. ??? ????? ??????? ??? ???????? ???. 1968 ??? ?????? ?? ???? ??? ????. \n");
    PreviewTextArea.setWrapStyleWord(true);
    PreviewTextArea.setCaretColor(new java.awt.Color(0, 0, 204));
    PreviewTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jScrollPane2.setViewportView(PreviewTextArea);

    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("@Developer: Priyanshu Patel");

    jLabel5.setBackground(new java.awt.Color(255, 255, 204));
    jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 0, 204));
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Typing Master");
    jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jLabel5.setOpaque(true);

    javax.swing.GroupLayout MainHomeScreenPanelLayout = new javax.swing.GroupLayout(MainHomeScreenPanel);
    MainHomeScreenPanel.setLayout(MainHomeScreenPanelLayout);
    MainHomeScreenPanelLayout.setHorizontalGroup(
        MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(MainHomeScreenPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainHomeScreenPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainHomeScreenPanelLayout.createSequentialGroup()
                    .addGroup(MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TimeDurationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(StartTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainHomeScreenPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4)
            .addContainerGap())
    );
    MainHomeScreenPanelLayout.setVerticalGroup(
        MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(MainHomeScreenPanelLayout.createSequentialGroup()
            .addGroup(MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(MainHomeScreenPanelLayout.createSequentialGroup()
                    .addGroup(MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(MainHomeScreenPanelLayout.createSequentialGroup()
                            .addGroup(MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(MainHomeScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TimeDurationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainHomeScreenPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(StartTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel4))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(MainHomeScreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(MainHomeScreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TimeDurationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeDurationComboBoxActionPerformed
        switch (TimeDurationComboBox.getSelectedIndex()) {
            case 0:
                timeDuration = 5;
                break;
            case 1:
                timeDuration = 10;
                break;
            case 2:
                timeDuration = 15;
                break;
            case 3:
                timeDuration = 30;
                break;
            case 4:
                timeDuration = 40;
                break;
            case 5:
                timeDuration = 50;
                break;
            case 6:
                timeDuration = 60;
                break;
        }
    }//GEN-LAST:event_TimeDurationComboBoxActionPerformed

    private void StartTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTestButtonActionPerformed
        TypingTestScreen tts = new TypingTestScreen(ExcerciseList.getSelectedValue(), previewString, timeDuration);
        tts.setVisible(true);
    }//GEN-LAST:event_StartTestButtonActionPerformed

    private void ExcerciseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ExcerciseListValueChanged

        onExcerciseSelected();
    }//GEN-LAST:event_ExcerciseListValueChanged

    private void onExcerciseSelected() {
        try {
            List<String> s = Files.readAllLines(Paths.get(langPath + "\\" + ExcerciseList.getSelectedValue() + ".txt"), Charset.forName("UTF-8"));

            previewString = s.get(0);
            for (int i = 1; i < s.size(); i++) {
                previewString += "\n" + s.get(i);
            }
            //System.out.println(s);
            //previewString+= "\n"+System.getProperty("file.encoding");
        } catch (IOException ex) {
            //JOptionPane.showMessageDialog(this,"Not Found! "+ ex.getMessage());
        }
        if (languageComboBox.getSelectedIndex() == 1) {
            previewString = previewString.substring(1);
        }
        PreviewTextArea.setText(previewString);
        PreviewTextArea.setCaretPosition(0);
        //PreviewTextArea.setFont(new java.awt.Font("Arial Unicode MS", 0, 22));
    }

    private void languageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageComboBoxActionPerformed

        onLanguageSelected();
    }//GEN-LAST:event_languageComboBoxActionPerformed

    String[] filelist;

    private void onLanguageSelected() throws HeadlessException {
        switch (languageComboBox.getSelectedIndex()) {
            case 0:
                langPath = "C:\\TypingTestByPRIYANHSHU\\English";
                break;
            case 1:
                langPath = "C:\\TypingTestByPRIYANHSHU\\Hindi";
                break;
        }

        try {
            filelist = new File(langPath).list();
            int i = 0;
            for (String s : filelist) {
                filelist[i++] = s.substring(0, s.length() - 4);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Path for content is not set!");
        }
        /*
        int i=0;
        for(String s: new File(langPath).list()){
            if(s.substring(s.length()-4).equals(".txt")){
                filelist[i++]=s;
            }
        }
         */
        ExcerciseList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = filelist;

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        ExcerciseList.setSelectedIndex(0);
        onExcerciseSelected();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypingHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypingHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypingHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypingHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TypingHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ExcerciseList;
    private javax.swing.JPanel MainHomeScreenPanel;
    private javax.swing.JTextArea PreviewTextArea;
    private javax.swing.JButton StartTestButton;
    private javax.swing.JComboBox<String> TimeDurationComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> languageComboBox;
    // End of variables declaration//GEN-END:variables

}
